### ISSUE TITLE
Error 500 while trying to sign a page

### ISSUE THREAD

**Issue by tombolliger** [baloise/digital-signature#100]
Hello

After upgrading from Confluence 7x to 8x digital-signature seems to be broken. All Pages we did sign before and also signing new page is not possible anymore. We get the Error below. 
Already tried to delete all the Plugin Cache but still got the error.
Thanks in advance for any hints, how to solve this issue. We really really depend on that AddOn.
Regards,
Tom

Error:
<status>
<status-code>500</status-code>
<stack-trace>java.lang.NullPointerException at com.baloise.confluence.digitalsignature.rest.DigitalSigatureService.sign(DigitalSigatureService.java:96) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.base/java.lang.reflect.Method.invoke(Unknown Source) at 
[digital-signature.txt](https://github.com/baloise/digital-signature/files/11158207/digital-signature.txt)

**Comment by keyless-tracer** [comment]
Hello, 
we have exactly the same problem as described by tom. All pages we did sign before and also signing new page is not possible anymore.
Error message:
<status>
<status code>500</status code>
<stack-trace>java.lang.NullPointerException at 
com.baloise.confluence.digitalsignature.rest.DigitalSigatureService.sign(DigitalSigatureService.java:96) at 
jdk.internal.reflect.GeneratedMethodAccessor5111.invoke(Unknown Source) at 
java.base/ jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at 
java.base/java.lang.reflect.Method.invoke(Method.java:566) at 
com.atlassian.plugins.rest.common.interceptor. impl.DispatchProviderHelper$ResponseOutInvoker.lambda$_dispatch$0(DispatchProviderHelper.java:181) at

**Comment by realignedtechnologies** [comment]
see #101

**Comment by Tiliavir** [comment]
See #82. This issue should no longer appear after a final Upgrade, Clear Plugin Cache and Restart.
