### ISSUE TITLE
Signatures are not displayed after upgrading Confluence

### ISSUE THREAD

**Issue by namyslok** [baloise/digital-signature#103]
Hi,

we have the same problem. Upgrade to Confluence version 8.3 Datacenter. Clearing the cache didn't improve anything. What is a fix?
Re-signing doesn't work either.

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<status>
<status-code>500</status-code>
<message>Cannot invoke "com.baloise.confluence.digitalsignature.Signature.sign(String)" because "signature" is null</message>
<stack-trace>Please contact your admin passing attached Log''s referral number: 43d6e53b-6c03-48d1-96d1-2dab2ae04e36</stack-trace>
</status>
With best regards
MaNa

**Comment by mpwilks2023** [comment]
This is happening on our Instance too. We're running 8.5.0 DC and at first we lost all signatures (they show as blank even though they were signed prior to the upgrade). When attempting to sign pages now, we receive the 500 error message as noted by @namyslok .

**Comment by Tiliavir** [comment]
This should be 7.0.7. Please upgrade, clear the plugin cache and restart confluence.
