### ISSUE TITLE
Data Center

### ISSUE THREAD

**Issue by trja1** [baloise/digital-signature#24]
Has this add-on been tested in the Data Center version of Confluence?

**Comment by culmat** [comment]
No. I never used data center products and I am not aware of what needs to be done to test / provision a plugin for DC usage.

**Comment by culmat** [comment]
https://developer.atlassian.com/platform/marketplace/developing-apps-for-atlassian-data-center-products/
All APIs used for the digital signatures are DC ready.
We have not yet tested. Obviously, for better scaling #1 should be fixed.

**Comment by CodeParanoia** [comment]
We are using this AddOn for months now in Data Center. No issues.

**Comment by Tiliavir** [comment]
Will as well be elaborated in #59
