### ISSUE TITLE
Position of the signature button should be flexible

### ISSUE THREAD

**Issue by pbaumi** [baloise/digital-signature#26]
Hey, very nice Add-On! As we alwayys have longer lists of signers (80+) AND have to integrate the macro in a page that people have to be able to read, it would be very nice to be able to specify the position of the signature-button and show/ hide the list of signers in the macro view (the list view in the background provides a complete overview). We'll try to figure something ourselves, any pointers would be highly appreciated. Thanks again for your great work!

**Comment by culmat** [comment]
Thanks for the compliment :-)
My first thoughts
1. count signatures
1. if more than <THRESHOLD> display only last <SOME> and and put the rest into a [expander](https://docs.atlassian.com/aui/5.2/docs/expander.html)

Should be quite straight forward to implement in [DigitalSignatureMacro.java](https://github.com/baloise/digital-signature/blob/master/src/main/java/com/baloise/confluence/digitalsignature/DigitalSignatureMacro.java) and [macro.vm](https://github.com/baloise/digital-signature/blob/master/src/main/resources/templates/macro.vm)

I guess less options are better. The macro parameter list grows fast and it will be increasingly difficult to maintain backwards compatablility.

**Comment by Tiliavir** [comment]
@culmat I've just pushed a first approach for this issue, implementing a threshold and some sort of expander logic.

**Comment by Tiliavir** [comment]
Hi @pbaumi 

This was fixed in 7.0.2. Upload to marketplace will be done in the next weeks - until then you can try / use the OBR from [our release repo](https://github.com/baloise/digital-signature/blob/gh-pages/7.0.2/digital-signature-7.0.2.obr).

Best regards
Markus
