### ISSUE TITLE
When a user leaves the macro no longer displays correctly.

### ISSUE THREAD

**Issue by bobbejokohler** [baloise/digital-signature#27]
We are using digital signature to approve releases in Confluence.  Our user base comes from JIRA / Crowd.  We had a manager leave who had approved the release.  The macro is now displaying a error message because the user is disabled.   

This is critical for our audit trails / security audits.

**Comment by culmat** [comment]
fix ist release to the marketplace https://marketplace.atlassian.com/apps/1217404/digital-signature?hosting=server&tab=versions
when a user gets deleted the user id is displayed and he is not included in mailings any more.

**Comment by bobbejokohler** [comment]
The macro is now rendering, however, this person used to be a manager and signed off.  Now that they are no longer here their check was removed.  In the future will this stay?  
![digital signature](https://user-images.githubusercontent.com/40030520/41488609-e6fcdf7c-70ba-11e8-9b6d-18cd2df80b60.png)

**Comment by culmat** [comment]
I can not explain nor reproduce the removed tick. 
Only the rendring of the name should change.
