### ISSUE TITLE
Compatibility update for Confluence version 6.11.0

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/digital-signature#30]
![image](https://user-images.githubusercontent.com/1764012/45229566-73bf8480-b2c6-11e8-8593-490c3821137f.png)

**Comment by MarkusTiede** [comment]
Next request
![image](https://user-images.githubusercontent.com/1764012/45471838-9c1a0980-b732-11e8-8642-7e68c089ab95.png)

**Comment by culmat** [comment]
FIXED see https://marketplace.atlassian.com/apps/1217404/digital-signature?hosting=server&tab=versions
