### ISSUE TITLE
Using plugin in a Template

### ISSUE THREAD

**Issue by moseisleydk** [baloise/digital-signature#31]
Using the Plugin in a Template gives us:

![image-2018-09-24-16-05-26-022](https://user-images.githubusercontent.com/15978685/46009572-480f0d80-c0c0-11e8-96bb-199ec168c515.png)

**Comment by MarkusTiede** [comment]
Hi @moseisleydk - thanks for reporting this! Do you happen to have some more information about the Atlassian instance you're currently using as well as maybe log-file excerpt?

@culmat : Could you tell from our side what might be causing the CCE?

**Comment by moseisleydk** [comment]
When my customer try to use it now:

Error rendering macro 'signature'

com.atlassian.confluence.pages.Draft cannot be cast to com.atlassian.confluence.pages.Page

![screenshot 2018-09-28 at 07 46 57](https://user-images.githubusercontent.com/15978685/46190170-b509e980-c2f2-11e8-9334-f58ad0d9ad04.png)

Confluence Version | 6.10.1
Build Number | 7702
Server Base URL | https://www.nspop.dk

CATALINA_OPTS | -XX:ReservedCodeCacheSize=256m -XX:+UseCodeCacheFlushing -Dconfluence.context.path= -Datlassian.plugins.startup.options='' -Dorg.apache.tomcat.websocket.DEFAULT_BUFFER_SIZE=32768 -Dsynchrony.enable.xhr.fallback=true -Xms2048m -Xmx5120m -XX:+UseG1GC -Datlassian.plugins.enable.wait=300 -Djava.awt.headless=true -XX:G1ReservePercent=20 -Xloggc:/pack/confluence/logs/gc-2018-08-14_07-41-05.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=2M -XX:-PrintGCDetails -XX:+PrintGCDateStamps -XX:-PrintTenuringDistribution
-- | --
JDK_JAVA_OPTIONS | --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED

**Comment by moseisleydk** [comment]
Any progress here? Can I help?

**Comment by MarkusTiede** [comment]
@moseisleydk : Thanks for the additional information - we're now able to reproduce and it's likely to be fixed in the upcoming weeks.

As a workaround for now: using the template as a page instance works (at least for us); so only previewing within the template context is currently broken.

**Comment by moseisleydk** [comment]
Same her, the macro renders when I press "Next" from the Template creation

**Comment by culmat** [comment]
tested and OK

**Comment by culmat** [comment]
Hi moseisleydk,
the fix is released.
Have fun.
Matthias
