### ISSUE TITLE
Atlassian  - add Privacy Policy 

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/digital-signature#36]
It is important to users to have trust in the Atlassian Marketplace. Improve that trust by including a Privacy Policy for users of your apps. This statement to users will be required after January 31st.  
As a reminder, receiving this email means that you have one or more apps that are not yet compliant. Add a URL linking to your privacy policy in the Data security and privacy statement field, located in the Details tab for that app in the Atlassian Marketplace vendor portal.  

Apps that are non-compliant with a legally sufficient Privacy Policy to users will be delisted from the Atlassian Marketplace after January 31st. Review the [Atlassian Marketplace Vendor Agreement](http://click.mailer.atlassian.com/?qs=b6a9e0814f7e507215dcce4d5ec099cf7ad23bb2e6f8829dc536d4b55979d9f95559f82bc5e61451cd122ba39f3ab1441d70aca03f6af7b5) section 8.4 for what is required.

Thank you,

The Atlassian team

**Comment by culmat** [comment]
See https://www.osnews.com/story/22233/the-difference-between-eulas-and-open-source-licenses/

**Comment by culmat** [comment]
https://ecosystem.atlassian.net/servicedesk/customer/portal/9/AMKTHELP-14932

**Comment by culmat** [comment]
See 
- https://github.com/baloise/digital-signature/blob/master/docs/privacy-policy.md
- https://ecosystem.atlassian.net/servicedesk/customer/portal/9/AMKTHELP-16056
