### ISSUE TITLE
digital-signature plugin not supporting Confluence 6.14

### ISSUE THREAD

**Issue by BarnaliPutatunda89** [baloise/digital-signature#37]
We are upgrading Confluenec to 6.14.2 & digital-signature plugin does not have a supported version. Could you please look into it.

**Comment by josiahsansone** [comment]
Same here for 6.13.3 - there was a critical sercurity advisory issued for older versions of Confluence which forced us to upgrade.  Would be nice if this add-on could be made compatible for the newer versions.
Thanks!

**Comment by reginvaldr** [comment]
Will you work on newer versions of Confluence? Or do you terminate this nice plugin? Is it possible to ask our Atlassian partner to take care of the requirements for keeping it in the Atlassian Marketplace? They do more plugin coding, maintenance and support.

**Comment by MarkusTiede** [comment]
Thanks for reporting this - we're currently not planning on terminating it; however we maintain this with best effort which might cause delays in response from time to time - sorry for that!

@culmat : could have a look into this?

**Comment by culmat** [comment]
Fixed.
