### ISSUE TITLE
Text Formatting

### ISSUE THREAD

**Issue by Jean-MichelBenkert** [baloise/digital-signature#4]
It is currently not possible to format the text in the signature box nicely, i.e., bold font, paragraphs, enumeration. This would be valuable, as it would allow for a more readable presentation of longer texts.

**Comment by culmat** [comment]
We won't provide full confluence rich text, because this would allow to render dynamic content that changes after the signature (i.e. external images) or to write white text on white background that would be part of the contract.
We could provide something like http://commonmark.org/help/ 
But that means no images, no tables, no macros, no colors, just very basic stuff and no WYSIWYG editor support (you will need to enter the markdown).

**Comment by Jean-MichelBenkert** [comment]
sounds great, should cover all we need! thx!


Jean-Michel Benkert
Group Strategy & Digital Transformation

Baloise Group, Aeschengraben 21, Postfach, CH - 4002 Basel
Telefon +41 58 285 75 04
jean-michel.benkert@baloise.com - www.baloise.com



Von:	Matthias Cullmann <notifications@github.com>
An:	baloise/digital-signature
            <digital-signature@noreply.github.com>,
Kopie:	Jean-MichelBenkert <jean-michel.benkert@baloise.com>, Author
            <author@noreply.github.com>
Datum:	07.08.2017 17:25
Betreff:	Re: [baloise/digital-signature] Text Formatting (#4)



We won't provide full confluence rich text, because this would allow to
render dynamic content that changes after the signature (i.e. external
images) or to write white text on white background that would be part of
the contract.
We could provide something like http://commonmark.org/help/
But that means no images, no tables, no macros, no colors, just very basic
stuff and no WYSIWYG editor support (you will need to enter the markdown).


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.




Disclaimer: The contents of this email and any attachment thereto are
intended exclusively for the attention of the addressee(s). The email and
any such attachment(s) may contain information that is confidential and
protected on the strength of professional, official or business secrecy
laws and regulations or contractual obligations. Should you have received
this email by mistake, you may neither make use of nor divulge the contents
of the email or of any attachment thereto. In such a case, please inform
the email's sender and delete the message and all attachments without delay
from your systems.
You can find our e-mail disclaimer statement in other languages under
http://www.baloise.ch/email_disclaimer
