### ISSUE TITLE
Option to hide list of users from the page.

### ISSUE THREAD

**Issue by bfrauen** [baloise/digital-signature#40]
Hi there,

we cannot use the macro Right now because the macro Displays all names of the users that Need to sign. This does not fit to our data security Policy. Can you add a configuration to the macro in order to hide the users?

Best regards
Björn from STAGIL

**Comment by MarkusTiede** [comment]
Hi @bfrauen - thanks for reporting this: I’ll get in contact with the maintainer and see whether we’ll add this functionality. Could you maybe add a few more information on what the expected behavior should look like? Thanks!

**Comment by bfrauen** [comment]
Hi Markus,

do you have any update on this for me?

1. In the first place the macro should just now Display all missing users:
![image](https://user-images.githubusercontent.com/8853061/65242623-c55c3b00-dae6-11e9-9732-bca2aac964fc.png)

2. Further improvements would be to have a configuration section where admins can define users/Groups that have permission to view missing signatures / done signatures.

Best regards
Björn

P.S. I'm waiting for a reply of my mail to group.ch_git@baloise.ch from the 26.08.2019. Can you please check and reply?

**Comment by MarkusTiede** [comment]
Hi @bfrauen - thanks for the additional information.

However I haven‘t heard anything so far from @culmat - I‘ll try again to get in touch with him. Otherwise we‘ll hand this over which might take some time - see #41 

For the eMail and upcoming reply I‘d recommend (resending) it to: Group.CH_Open-Source@baloise.ch - the first one we‘re no longer actively maintaining.

**Comment by MarkusTiede** [comment]
Maybe to speed this up: would it be an option to implement this yourself? We‘d be happily integration PRs that would come for the project.

**Comment by culmat** [comment]
Hi @bfrauen,
please update to v7.0.1 ( released to the marketplace ).
Any comments welcome.
CU
Matthias
