### ISSUE TITLE
Request support for Confluence Version 7+

### ISSUE THREAD

**Issue by ngeraci0318** [baloise/digital-signature#43]
Our organization just updated to Confluence version 7 and the digital-signature macro is no longer compatible. Is there a way to make this macro compatible with v7+ ?

**Comment by MarkusTiede** [comment]
Hey @ngeraci0318 - thanks for your request. There sure is a way: I‘ll have to check in which timeframe.

**Comment by ngeraci0318** [comment]
Thanks so much! I look forward to hearing back about the timeline – we’ve really come to rely on the signature feature at our company and would love to get it back!

**Comment by culmat** [comment]
updated to v7.0.4
