### ISSUE TITLE
Contract titel

### ISSUE THREAD

**Issue by n102142** [baloise/digital-signature#46]
Hello everyone,

is it possible to configure that the contract titel is always the document titel, maybe with a variable?

Thank you!

**Comment by culmat** [comment]
Hello n102142,

yes this is totally possible. We could use a magic word i.e _$pageTitle_ to indicate that the title should be inherited from the page.

The draw back I see is:  it is encouraging people to have the contract content in the page and use the signature macro only with minimal text, though only the content of the macro is hashed into the signature. See [Signature Macro Usage](https://github.com/baloise/digital-signature/wiki/Signature-Macro-Usage)

> Please be aware the containing page can still be modified so the signature only applies to the content inside macro title and body. You don't sign the page but the content of the contract.

Wouldn't this be misleading? 
Best regards.
Matthias

**Comment by Jokabu2** [comment]
Hello Matthias, 

thank you!

Yes I see you point. We use this marco in a different context. Somebody creates a new page by using a template. At the top is the content and documentation and in the bottom of the page there is the sign macro. We use the sign to approve the Confluecne page.

Best regards.
Tomas

**Comment by culmat** [comment]
Hello Tomas,

IMHO this is a similar but different use case - it is a page approval, not a contract. 
After approval can you still edit the page?
What shall than happen to the signature?
I guess the signature should be linked to the content of the page ( storage format)? ( Knowing that with page includes and other macros the content can change on every refresh )
We could have a body-less  macro ( I don't see the need for title and body?)

I guess we could also go light on the other parameters ( like protected child page - do you need that? )

What do you think?
Best regards.
Matthias

**Comment by Jokabu2** [comment]
Thank you for the input. The different points you asked are very helpful but we only want to use the very basic functionalities. 

Thank you!

**Comment by Tiliavir** [comment]
Hi @Jokabu2

One of the following macros, designed solely for the use case you describe, might better fit your needs:

- https://marketplace.atlassian.com/apps/144/page-approval-for-confluence
- https://marketplace.atlassian.com/apps/1216387/approvals-for-confluence

However, this is an interesting scenario we might want to pick up for a new macro in the future.

Best regards
Markus
