### ISSUE TITLE
Signed signature not showing up on confluence page

### ISSUE THREAD

**Issue by ankyptl** [baloise/digital-signature#55]
When someone clicks on sign as button, I get the email that it was signed, however, when I go to the confluence page the approval does not show up.

**Comment by Tiliavir** [comment]
Hi @ankyptl 

that sounds strange - was the content of the signature panel changed in the mean time?

Can you give any hints what could have caused that behavior or even how to reproduce it?
Does the panel e.g. look broken in any way, except that the signature is missing? Are there warnings in the browser console, etc?

Thanks for the bug report
Markus

**Comment by Tiliavir** [comment]
closed due to missing feedback.
