### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com until 2020-12-31

### ISSUE THREAD

**Issue by christiansiegel** [baloise/digital-signature#56]
travis-ci.**org** will be closed down December 31st, 2020

Announcement: https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom
Migration guide: https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by Tiliavir** [comment]
Using github actions instead.
