### ISSUE TITLE
Error messege: You need to enter at least 10 characters of text to be signe - Addin Digital Signature

### ISSUE THREAD

**Issue by AnnaOlenberg** [baloise/digital-signature#58]
Hi dear support-team, 
we use your addin for Confluence Signature Panel.
After our update to Confluence 7.4.6 and update of your addin to 7.0.1 we get this error messege: 
You need to enter at least 10 characters of text to be signed.
![image](https://user-images.githubusercontent.com/77107399/103894778-b2141b00-50ef-11eb-89e7-fcfa42b4710c.png)

Even though the panel title has 10 characters, the errors still gets shown and no signature is possible. 

Can you help us?
Thanks and best, 
Anna

**Comment by Tiliavir** [comment]
Hi @AnnaOlenberg 

I think this error message refers to the content/contract of the panel, that can be signed and not the title.
Since you are still in the process of adding the panel to the site, there is not content and the preview shows a warning. You should never the less be able to add the panel to your page and add content afterwards.

This might not be too intuitive, but is correct from my point of view...

Best regards
Makus

**Comment by AnnaOlenberg** [comment]
Hallo Markus,
thanks!
It works.
Best, Anna


Tel.: +49833460137109
MULTIVAC Info Box
MULTIVAC
Sepp Haggenmüller SE & Co. KG - Bahnhofstr. 4 - D-87787 Wolfertschwenden - Germany
Tel.: +49(0)8334/601-0 - Fax: +49(0)8334/601-199 - multivac@multivac.de
Kommanditgesellschaft 
Sitz: 87787 Wolfertschwenden  Amtsgericht: Memmingen 
HRA 8040

USt-IdNr.: DE 129082475 -
Steuer-Nr.: 138/169/51105 - WEEE-Reg.-Nr.: DE 16576440
Persönlich haftende
Gesellschafterin: MULTIVAC Sepp Haggenmüller Verwaltungs SE
Sitz:
87787 Wolfertschwenden  Amtsgericht: Memmingen HRB 16659
Geschäftsführende Direktoren:
Guido Spix, Christian Traumann

Verwaltungsratsvorsitzender: Robert Vetter
Bankverbindung: Deutsche Bank
Memmingen . IBAN: DE 31 7337 0008 0123 6330 00 . BIC:
DEUT DE MM 733





Banner
Banner
Von: Markus Lindenmann [mailto:notifications@github.com]
Gesendet: Donnerstag, 14. Januar 2021 15:19
An: baloise/digital-signature <digital-signature@noreply.github.com>
Cc: Anna Olenberg <anna.olenberg@multivac.de>; Mention <mention@noreply.github.com>
Betreff: Re: [baloise/digital-signature] Error messege: You need to enter at least 10 characters of text to be signe - Addin Digital Signature (#58)

EXTERNAL MAIL

Hi @AnnaOlenberg<https://github.com/AnnaOlenberg>

I think this error message refers to the content/contract of the panel, that can be signed and not the title.
Since you are still in the process of adding the panel to the site, there is not content and the preview shows a warning. You should never the less be able to add the panel to your page and add content afterwards.

This might not be too intuitive, but is correct from my point of view...

Best regards
Makus

**Comment by Tiliavir** [comment]
Thank you very much for your feedback and glad it works!
