### ISSUE TITLE
Test compatibility for data center version of Atlassian Confluence

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/digital-signature#59]

**Comment by Tiliavir** [comment]
There is no official data center docker image as documented e.g. here: https://github.com/codeclou/docker-atlassian-confluence-data-center

But I found this one and will try to get it up and running within the next days: https://github.com/codeclou/docker-atlassian-confluence-data-center

**Comment by Tiliavir** [comment]
Data Center App Development Guidelines https://developer.atlassian.com/platform/marketplace/guidelines-for-data-center-app-development/
Check App using https://developer.atlassian.com/server/confluence/confluence-data-center-plugin-validator/

**Comment by Tiliavir** [comment]
Since multiple users are already using digital-signature on Confluence's data center version this task will be closed. Digital-signature is therefore considered to support the data-center version as-is.

**Comment by Tiliavir** [comment]
Continued in #72 in cooperation with our bitbucket codefreeze plugin.
