### ISSUE TITLE
Error after updating to version 7.0.2

### ISSUE THREAD

**Issue by williamtanner17** [baloise/digital-signature#61]
We just updated the digital-signature plugin for Confluence to version 7.0.2.  After the update, when we click the button "Sign as ..." we get a page displaying a bunch of XML.  I have attached a screen shot.

Is this a bug or is there something we need to do on our end?

![digital-signature](https://user-images.githubusercontent.com/77806718/105405877-a8170f80-5bf9-11eb-8d80-d05551af8726.jpg)

**Comment by Tiliavir** [comment]
Hi @williamtanner17 

Thank you for reporting the issue!
Could you provide your confluence server version? I'll try to reproduce it specifically with that vesion.

Best regards
Markus

**Comment by williamtanner17** [comment]
Hi Markus,

We discovered this during testing after upgrading our Test environment to Confluence Data Center 7.10.1.

Regards,

Bill


[cid:image001.png@01D6F0B3.F6C1B330]
William Tanner
Maestro
U.S. Department of Homeland Security
OCIO | CTOD | TA&E (Contractor Support)
[A picture containing clipart  Description automatically generated]
Empowering teams to work together, through intuitive solutions.

**Comment by culmat** [comment]
Hello Bill,

do you get this error on all macro instances or only on some?
Can you create a new macro with v7.0.2 and sign it?
Does the export work?

![image](https://user-images.githubusercontent.com/638519/105741531-b1c2af00-5f3a-11eb-9cd5-5fe4e1eec531.png)

Best regards.
Matthias

**Comment by MarkusTiede** [comment]
Hello @williamtanner17  - thanks for reporting to this: do you have additional information as requested?

**Comment by williamtanner17** [comment]
Hello Markus,

Sorry for the delayed response.  Somehow, I missed the last email notification update.

I tested the plugin this morning to answer your questions and everything is working fine.  I have no idea what changed.  I'll assume this is resolved unless you would like to try and determine what initially happened.

**Comment by MarkusTiede** [comment]
Thanks for the quick response @williamtanner17 - resolving for now: feel free to reopen if it re-occurs.
