### ISSUE TITLE
Is Data Center Version planned?

### ISSUE THREAD

**Issue by NamaSayaAkilan** [baloise/digital-signature#66]
We are using Confluence Data Center Version 6.15.7 and would like to use Digital-Signature Add On. 
Since it is stated, that at the moment only the server version of Digital-Signature is available, we would like to know if a Data Center version is planned at all?
Thank you very much for your help in advance.

**Comment by Tiliavir** [comment]
Hi @NamaSayaAkilan 

It will be tested with #59 for the data center version of confluence. However, this is postponed a couple of months - I hope it will be possible as for Q3 2021.

That said, it might even work as is in the data center version but that is without any warranty and untested.

Best regards
Markus
