### ISSUE TITLE
Error on some digital signature macros

### ISSUE THREAD

**Issue by williamtanner17** [baloise/digital-signature#68]
We are seeing errors on some digital signature macros, while others work fine.  We even have the same page with the same macro in our Test and Production environments, and the macro works in Test, but not in prod.  The error we see on the page is:

Error rendering macro 'signature'

com.baloise.confluence.digitalsignature.Signature cannot be cast to com.baloise.confluence.digitalsignature.Signature
[digital-signature-error-log.txt](https://github.com/baloise/digital-signature/files/6314735/digital-signature-error-log.txt)

**Comment by Tiliavir** [comment]
Hi @williamtanner17 

Very interesting - which version of digital-signature and confluence are you using?

```
java.lang.ClassCastException: com.baloise.confluence.digitalsignature.Signature cannot be cast to com.baloise.confluence.digitalsignature.Signature
	at com.baloise.confluence.digitalsignature.DigitalSignatureMacro.sync(DigitalSignatureMacro.java:294)
	at com.baloise.confluence.digitalsignature.DigitalSignatureMacro.execute(DigitalSignatureMacro.java:97)
```

Best regards
Markus

**Comment by williamtanner17** [comment]
Hello Markus,

We are on Confluence Data Center 7.10.1.  We just updated digital-signature to version 7.0.3.

Regards,

Bill

**Comment by Tiliavir** [comment]
Hi @williamtanner17 

It seems your deployment state is somehow corrupted. The error from the log file you provided indicates, that you are still on version 7.0.2, cause in 7.0.3 line 294 is empty:

- https://github.com/baloise/digital-signature/blob/7.0.3/src/main/java/com/baloise/confluence/digitalsignature/DigitalSignatureMacro.java#L294
- https://github.com/baloise/digital-signature/blob/7.0.2/src/main/java/com/baloise/confluence/digitalsignature/DigitalSignatureMacro.java#L294

Can you verify that the deployment was successful?

Best regards
Markus

**Comment by TrooperNo5** [comment]
Hello there,

we encounter the same behavior. Confluence (Server) is on version 7.10.1 (since January 2021) and the macro says it is on version 7.0.3. How can we verify that the deployment was successful?

Best regards
Christian

**Comment by williamtanner17** [comment]
We resolved the problem by uninstalling the plugin, clearing the plugin cache, and reinstalling the plugin.  A restart of each node is also required as part of clearing the plugin cache.

**Comment by TrooperNo5** [comment]
@williamtanner17 Thanks for the hint. It was sufficient for us to clear the plugin cache and restart Confluence. Problem is solved for now.

Best regards
Christian

**Comment by Tiliavir** [comment]
Thank you very much for the update @williamtanner17 and @TrooperNo5!

Glad that the issue is resolved for both of you - I will keep the task open, I think that is worth some kind of documentation in particular since we want to test data center compatibility with #59. 

FYI: @culmat
