### ISSUE TITLE
Remove the mandatory limit of "10 characters minimum" to create the sign form ?

### ISSUE THREAD

**Issue by sleduc82** [baloise/digital-signature#74]
Greetings !
I would like to know if it is possible to remove this constraint or limit it to 1 or 2 characters, or just a tick box ?
Thanks
Great job !
Regards
Sleduc

**Comment by Tiliavir** [comment]
Hi @sleduc82 

The basic idea of digital-signature is to "sign" a contract that is contained in the plugins body. Removing this body will more or less render it useless. It is not meant to be used as a page approval.

Could you maybe elaborate your use case a bit? Maybe I can provide you better feedback knowing what you are trying to achieve.

Best regards
Markus

**Comment by sleduc82** [comment]
Hello Tiliavir,
Thanks for the feedback : my customer would like to only tick a box, or maybe if we could use a body template ?
Regards
Sleduc

**Comment by Tiliavir** [comment]
Hi @sleduc82 

We had a similar discussion in #46. I'm still not sure what your exact use case is but is it the same as or similar the the linked issue?

By body template you mean something like a set of predefined options that can be administered by super users and chosen from when adding the webpart to a page?

Best regards
Markus

**Comment by sleduc82** [comment]
Hi,
I understand what you mean "Removing this body will more or less render it useless" and the principle of a digital signature.
But I think that my customer would indeed " to be used as a page approval" or so, and would like to remove this limitation of 10 char minimum.
Would it be possible to add this possibility ?
Thank you in advance.
Regards

**Comment by Tiliavir** [comment]
Hi @sleduc82 

Technically it would indeed be possible. However I don't think it's a good idea since the use case this plugin addresses is another one.

In #46 we suggested the use of a couple of alternatives.

What are your thoughts @culmat , @MarkusTiede ?

Best regards
Markus
