### ISSUE TITLE
Plans to release version compatible with Confluence 7.13

### ISSUE THREAD

**Issue by vcknapp** [baloise/digital-signature#76]
Hello, we have a customer who uses this add-on but when they upgraded Confluence, they found the app isn't supported / isn't a compatible version anymore. Please can you confirm if you will release a new version of digital-signature for Confluence 7.13? Thank you. Valerie

**Comment by vcknapp** [comment]
Please can you also comment on whether there is a roadmap for either Data Center or Cloud versions of the add-on? The customer is going to migrate to Data Center soon so they would also ideally like to continue using this add-on if possible.

**Comment by Tiliavir** [comment]
Hi @vcknapp 

A official data center version is planned with #72 however you can already use the current version:

> Digital-signature can be used on Confluence Data Center, however it is not yet officially tested and approved. When performing an update you might have to invalidate the plugin cache and restart Confluence. For details refer to #68.

I will take care for a new version of digital signature supporting confluence 7.1.13 next week.

Best regards
Markus

**Comment by mcnema** [comment]
Hi Markus,

Hope all is well.

i am checking in to confirm on the release date of the new add-on to be compatible with Confluence version 7.13.0

Thanks,
Matthew

**Comment by vcknapp** [comment]
Hi @Tiliavir,
My customer is also asking when the new version will be released. Please can you confirm?

Thanks,
Valerie

**Comment by MarkusTiede** [comment]
Hello @mcnema & @vcknapp : we are releasing new versions as the requirements arise from our own, internal use.

I will check with @Tiliavir whether we can provide you with an update in a short term. 

Would you be otherwise be willing to contribute this e.g. on your own?

**Comment by MarkusTiede** [comment]
We'd be interested in merging proposed modifications in form of a PR.

**Comment by vcknapp** [comment]
Hi @MarkusTiede, 
Thanks for your message. I don't know what that means, sorry. I understood there was going to be a new version of the app, digital-signature. My customer needs a version that is compatible with Confluence 7.13 so I am asking on their behalf.
Thanks,
Valerie

**Comment by Tiliavir** [comment]
Hi @vcknapp, @mcnema,

Please have a look on the [Atlassian Marketplace](https://marketplace.atlassian.com/apps/1217404/digital-signature?tab=overview&hosting=server). Version 7.0.3 is ready for Confluence 7.13.

Best regards
Markus

**Comment by MarkusTiede** [comment]
Idea: https://github.com/baloise/open-source/issues/316
