### ISSUE TITLE
Support Confluence version higher 7.14

### ISSUE THREAD

**Issue by RegentRon** [baloise/digital-signature#78]
The latest version (7.0.3) does not seems to work with Confluence Data Center (7.14.1)

The macro prints only an error:
Error rendering macro 'signature'

could not execute statement; SQL [n/a]; constraint [bandana_unique_key]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

**Comment by MarkusTiede** [comment]
Thanks @RegentRon for reporting: @Tiliavir (could you quickly elaborate whether) we do need additional information for analyzing?

**Comment by Tiliavir** [comment]
Hi @RegentRon

I've adjusted the version in the atlassian marketplace. There is a known issue with DC at the moment.
Nevertheless you can still use it, only have to clear the plugin cache after upgrading.

Compatibility for DC with an official DC release is planned in #78.

Sorry for the inconvenience
Markus

**Comment by RegentRon** [comment]
Hi @Tiliavir 

after clearing of the cache seems the plugin to be working. Thanks for the hint.

If I should test something special for DC please let me know.

**Comment by MarkusTiede** [comment]
Thanks for offering help @RegentRon we'll get back to you!
