### ISSUE TITLE
Notify users who have to sign

### ISSUE THREAD

**Issue by rotalf** [baloise/digital-signature#8]
It is possible to implement the @Mention function in the macrobody, so that the users who have to sign be notified.
Or users are notified automatically.

**Comment by culmat** [comment]
Not sure when to send the email and if it is not considered to be spam.
We could send the email to every receipient only once per contract. Still every change in the signers, i.e. changing the inheritSigners in edit mode and refreshing the preview would send our the emails.

You can easily send an email to all missing signatures using the email drop down 
![image](https://user-images.githubusercontent.com/638519/29212166-5bd9a99e-7e9d-11e7-9ece-e93c7b2979ac.png)

So you are in control of when to send the email.
Is this a sufficient solution?

**Comment by rotalf** [comment]
Yes this is a sufficient solution 
Thank you

**Comment by culmat** [comment]
you are welcome :-)
