### ISSUE TITLE
Digital signature - not working - Confluence server 7.13.2 - plugin 7.0.4

### ISSUE THREAD

**Issue by vcknapp** [baloise/digital-signature#84]
Hello,

We have the same problem that is already reported in issue where the Signatures in the page have stopped being rendered with this error message:
![digital_signature_plugin_error](https://user-images.githubusercontent.com/90238913/148903893-293494fc-2e58-4f93-902a-3229ffd878e1.png)

Please can someone help?

Thank you,
Valerie

**Comment by vcknapp** [comment]
Please @Tiliavir, can you take a look at this issue?

**Comment by Tiliavir** [comment]
Hi @vcknapp 

please have a look at #82 

Best regards
Markus
