### ISSUE TITLE
Digital Signature not work

### ISSUE THREAD

**Issue by billikill** [baloise/digital-signature#85]
Hello, after update confluence to version 7.13.3, plugin verssion 7.0.4 don`t work. 
When the user clicks on the button "Sign as ..", the signature is not put.
![image](https://user-images.githubusercontent.com/33964260/149921191-f7fddd1d-c9f9-4a15-a30f-bf77766c806b.png)

**Comment by billikill** [comment]
No errors in the log

**Comment by Tiliavir** [comment]
Hi @billikill 

Do you see errors in the widget or in the browser console?

Markus

**Comment by billikill** [comment]
Hi @Tiliavir 
I got what is the problem.  If there are 2 macros into one page then macros doesn't work. Thanks for your support.
