### ISSUE TITLE
Error running 'signature'

### ISSUE THREAD

**Issue by oberfeld-finstreet** [baloise/digital-signature#86]
Hi, i got the following error, after update the plugin. Nothing else changed.

`class com.baloise.confluence.digitalsignature.Signature cannot be cast to class com.baloise.confluence.digitalsignature.Signature (com.baloise.confluence.digitalsignature.Signature is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @72b5bbb1; com.baloise.confluence.digitalsignature.Signature is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @554edc2c)`

**Comment by Tiliavir** [comment]
Hi @oberfeld-finstreet 

We are currently working on a fix for that issue in #82.
For now the only workaround fornthelat issue is, to reset the plugin cache and restart confluence.

I'm sorry for the inconvenience
Markus
