### ISSUE TITLE
Digital Signature Enquiry

### ISSUE THREAD

**Issue by Mattymcn95** [baloise/digital-signature#87]
Hi All,

We currently use Digital Signature version 7.0.4 as part of our Confluence Server Instance.

From test page of the images below are we able to configure the add-on to move the Sign as (your username) button to the top of the page rather than the bottom?

Thanks,
Matthew

<img width="720" alt="signature one" src="https://user-images.githubusercontent.com/26100308/152531481-eeb9235e-8d02-4f19-9485-5fd44d8b912e.png">
<img width="223" alt="signature two" src="https://user-images.githubusercontent.com/26100308/152531500-0f388fc3-bc91-4920-ac09-cd8fb0a026b6.png">

**Comment by Tiliavir** [comment]
Hi @Mattymcn95 

this feature request was previously discussed in #26 and at that time rejected, to keep the configuration as easy as possible. However, #26 was addressed by providing a way to collapse the signee list to a "limit of visible signees" to handle such long lists:

![image](https://user-images.githubusercontent.com/8123039/152643876-6aa1285d-6b19-4ff3-852e-60196b20f2a5.png)

Please let me know if this helps or if you have other pro / con arguments for that point.

Best regards
Markus
