### ISSUE TITLE
Testing for cloud

### ISSUE THREAD

**Issue by zbalkan** [baloise/digital-signature#89]
I have just started evaluating this solution on out server instance. It worked flawlessly yet we are migrating to the cloud very soon.

Since I have no data that would be affected by the backwards compatibility, I can test the alpha/beta versions in my cloud environment.

What can I do to help?

**Comment by Tiliavir** [comment]
In https://github.com/baloise/digital-signature/issues/78 @RegentRon offered help in testing the DC version.

Currently DC and Cloud versions are waiting for a fix in https://github.com/baloise/digital-signature/issues/82. As soon as we have a breakthrough there, I will happily come back to the two of you :-)
