### ISSUE TITLE
email list does not work properly

### ISSUE THREAD

**Issue by Jean-MichelBenkert** [baloise/digital-signature#9]
when I use the email functionality not all the names are included in the email. it seems there is a limit, as the last name which was included was not complete.

**Comment by culmat** [comment]
The limit is browser / mail client specific. On Lotus Notes 8.5 it seems to be 1280 characters. 
We could either leave off the names "x y<x.y@z.com>" ->  "x.y@z.com" as soon as the Text gets long (> 500 chars) or have a minmal online mail editor (subject, body, no rich text, no attachments) and send the mail through browser / server instead of native mail client. Then wi could also use confluence inbuilt notification service.

**Comment by Jean-MichelBenkert** [comment]
Both sound fine to me. Copying the emails to the clipboard sounded good,
too. Conclusion: Whatever you deem best!

thank you!


Jean-Michel Benkert
Group Strategy & Digital Transformation

Baloise Group, Aeschengraben 21, Postfach, CH - 4002 Basel
Telefon +41 58 285 75 04
jean-michel.benkert@baloise.com - www.baloise.com



Von:	Matthias Cullmann <notifications@github.com>
An:	baloise/digital-signature
            <digital-signature@noreply.github.com>,
Kopie:	Jean-MichelBenkert <jean-michel.benkert@baloise.com>, Author
            <author@noreply.github.com>
Datum:	14.08.2017 17:00
Betreff:	Re: [baloise/digital-signature] email list does not work
            properly (#9)



The limit is browser / mail client specific. On Lotus Notes 8.5 it seems to
be 1280 characters.
We could either leave off the names "x yx.y@z.com" -> "x.y@z.com" as soon
as the Text gets long (> 500 chars) or have a minmal online mail editor
(subject, body, no rich text, no attachments) and send the mail through
browser / server instead of native mail client. Then wi could also use
confluence inbuilt notification service.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.




Disclaimer: The contents of this email and any attachment thereto are
intended exclusively for the attention of the addressee(s). The email and
any such attachment(s) may contain information that is confidential and
protected on the strength of professional, official or business secrecy
laws and regulations or contractual obligations. Should you have received
this email by mistake, you may neither make use of nor divulge the contents
of the email or of any attachment thereto. In such a case, please inform
the email's sender and delete the message and all attachments without delay
from your systems.
You can find our e-mail disclaimer statement in other languages under
http://www.baloise.ch/email_disclaimer
