### ISSUE TITLE
Community License

### ISSUE THREAD

**Issue by Tommygitas** [baloise/digital-signature#92]
Hello dear Github Team,

we have a customer who is currently your product as a community license in the server version. Now they are changing to the Data Center version, but your product isn't available there.

Is there any plans in the pipeline to bring a DC version? 

Are there any alternatives to your product?

Thank you very much in advance.

Best regards
Chrysostomos Gitas

**Comment by Tiliavir** [comment]
Hi @Tommygitas 

we are currently working on this in https://github.com/baloise/digital-signature/issues/72 - unfortunately this is waiting for https://github.com/baloise/digital-signature/issues/82 at the moment. If that is fixed we will push the DC ready version and update the issue accordingly.

Best regards
Markus

**Comment by Tommygitas** [comment]
Hello Markus,

thanks for your feedback.

Are there any news regarding the 2 issues?

Best regards
Tommy

[cid:signatur_4_logo_170x120px_66082ac2-21b1-4a1f-8e06-8916f082968e.png]<https://www.actonic.de/>
Chrysostomos Gitas
Sales Manager
Tel.: +49 (0) 151 / 42084409
Fax: +49 7042 / 971 497 5

Discover our products on actonic.de<https://www.actonic.de/en/products>
Actonic GmbH, An der Schelmenhalde 35,
71665 Vaihingen an der Enz, Germany
Office Stuttgart: Fuchseckstraße 7, 70188 Stuttgart, Germany
Registergericht: Amtsgericht Stuttgart, HRB 752628
Geschäftsführer: Domenico Manzo & Gregor Kasmann
USt-ID: DE300387436
[cid:linkedin-small_11c9f6f7-0ff8-4c2b-a25d-f65c015a1e97.png] <https://www.linkedin.com/company/13072629> [cid:fb_0b5fff1f-92bd-4b9c-b87c-a2cfe1f84be2.png]  <https://www.facebook.com/actonic.de> [cid:youtube_0626b011-5b09-4d41-bd0b-93718fca8481.png]  <https://www.youtube.com/channel/UCeqKjaaMm3w5hvO5UpDN15w> [cid:twitter_951dcfa3-922c-4729-94b3-b553bc180155.png]  <https://twitter.com/actonic_de> [cid:xing_8a5a809d-64ab-433a-9a62-c759b0b152e9.png]  <http://xing.com/companies/actonic>

[cid:we-are-hiring_a1f66106-ff8f-4eee-88a2-f0a92562bdaf.jpg]<https://www.actonic.de/en/jobs/?utm_source=e-mail&utm_medium=signature&utm_campaign=e-mail+signature>
The information contained in this message is confidential. It may also be privileged or otherwise protected by legal rules. The use of this information by others than the named addressee(s) is not allowed. If you are not the intended recipient of the message, please let us know by reply and then delete the message (including any attachment) from your system; you should not copy it or disclose its contents to anyone. Emails are not secure and cannot be guaranteed to be error free as they can be intercepted, amended, lost or destroyed, or contain viruses. Anyone who communicates with us by email is taken to accept these risks.

________________________________
Von: Markus Lindenmann ***@***.***>
Gesendet: Donnerstag, 5. Mai 2022 13:32
An: baloise/digital-signature ***@***.***>
Cc: Chrysostomos Gitas ***@***.***>; Mention ***@***.***>
Betreff: Re: [baloise/digital-signature] Community License (Issue #92)


Hi @Tommygitas<https://github.com/Tommygitas>

we are currently working on this in #72<https://github.com/baloise/digital-signature/issues/72> - unfortunately this is waiting for #82<https://github.com/baloise/digital-signature/issues/82> at the moment. If that is fixed we will push the DC ready version and update the issue accordingly.

Best regards
Markus
