### ISSUE TITLE
Digital Signature Data Center question

### ISSUE THREAD

**Issue by Mattymcn95** [baloise/digital-signature#93]
Hi All,

As per image below we are currently widely using your add-on on our Jira Server instance on the latest version.

<img width="575" alt="digitial signature add-on" src="https://user-images.githubusercontent.com/26100308/169287090-8f488fa9-369e-407c-8cb8-9cd67950f725.png">

we are currently using your product in the server version of Confluence. Now we are planning to changing to the Data Center version when we migrate Jira and Confluence etc to firstly a single node data center, but your product isn't available there.

Is there any plans in the pipeline to bring a DC version to fit this purpose?

Thank you in advance.

Best regards
Matthew

**Comment by Tiliavir** [comment]
Hi @Mattymcn95 

please refer to https://github.com/baloise/digital-signature/issues/72 for details.
I'm closing this one as duplicate.

Best regards
Markus
