### ISSUE TITLE
Plugin availability for higher version of confluence

### ISSUE THREAD

**Issue by arwavis** [baloise/digital-signature#96]
Hi Team,

We recently upgraded our confluence to version 7.17.4 from 7.13.2 and we see that this plugin "digital-signature" is not available for the latest version of confluence, Is there any plans to release this plugin for the latest version of confluence.

We are still running Confluence Server Version.

Regards
Aravind Viswanathan.

**Comment by arwavis** [comment]
Hi Team,

Could you please provide us an update?

Regards
Aravind Viswanathan.

**Comment by arwavis** [comment]
Hi Team,

Could you please provide us an update?

Regards
Aravind Viswanathan.

**Comment by culmat** [comment]
Hi @arwavis , we have released the current plugin version for the confluence server up until 7.18.2. 
Best regards,
Matthias

**Comment by arwavis** [comment]
Awesome, Thanks 

All looks good.
